language: go

dist: trusty
sudo: false

os:
  - linux
  - osx

services:
  - neo4j

go:
  - 1.6
  - 1.7
  - tip

script: RECORD_OUTPUT=1 NEO4J_BOLT=bolt://neo4j:neo4j@localhost:7687 go test -v ./... 
